### ISSUE TITLE
python environment

### ISSUE THREAD

**Issue by RickRen-rpr** [JohnGiorgi/seq2rel#388]
Hello, can you export and share your python environment, I'm having trouble installing the package, I'm looking forward to your reply.

**Comment by JohnGiorgi** [comment]
Hi, maybe you could provide the traceback of the errors you are facing, and I can try and help debug it that way?

I just re-ran the [training notebook](https://colab.research.google.com/github/JohnGiorgi/seq2rel/blob/main/notebooks/training.ipynb), and everything seems to install correctly on colab

**Comment by RickRen-rpr** [comment]
Thanks, I am having the following problem with poetry install:
poetry install
Installing dependencies from lock file

```
Package operations: 27 installs, 13 updates, 0 removals

  • Updating charset-normalizer (2.0.4 -> 2.1.0)
  • Updating jsonnet (0.17.0 /home/conda/feedstock_root/build_artifacts/jsonnet_1667026987235/work -> 0.18.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  running bdist_wheel
  running build
  running build_ext
  g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json -Ithird_party/rapidyaml/rapidyaml/src/ -Ithird_party/rapidyaml/rapidyaml/ext/c4core/src/ core/desugarer.cpp -o core/desugarer.o
  g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json -Ithird_party/rapidyaml/rapidyaml/src/ -Ithird_party/rapidyaml/rapidyaml/ext/c4core/src/ core/formatter.cpp -o core/formatter.o
  g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json -Ithird_party/rapidyaml/rapidyaml/src/ -Ithird_party/rapidyaml/rapidyaml/ext/c4core/src/ core/libjsonnet.cpp -o core/libjsonnet.o
  g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json -Ithird_party/rapidyaml/rapidyaml/src/ -Ithird_party/rapidyaml/rapidyaml/ext/c4core/src/ core/lexer.cpp -o core/lexer.o
  g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json -Ithird_party/rapidyaml/rapidyaml/src/ -Ithird_party/rapidyaml/rapidyaml/ext/c4core/src/ core/parser.cpp -o core/parser.o
  g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json -Ithird_party/rapidyaml/rapidyaml/src/ -Ithird_party/rapidyaml/rapidyaml/ext/c4core/src/ core/pass.cpp -o core/pass.o
  g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json -Ithird_party/rapidyaml/rapidyaml/src/ -Ithird_party/rapidyaml/rapidyaml/ext/c4core/src/ core/static_analysis.cpp -o core/static_analysis.o
  g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json -Ithird_party/rapidyaml/rapidyaml/src/ -Ithird_party/rapidyaml/rapidyaml/ext/c4core/src/ core/string_utils.cpp -o core/string_utils.o
  g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json -Ithird_party/rapidyaml/rapidyaml/src/ -Ithird_party/rapidyaml/rapidyaml/ext/c4core/src/ core/vm.cpp -o core/vm.o
  In file included from third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/config.hpp:35:0,
                   from third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/substr.hpp:10,
                   from third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/std/string.hpp:6,
                   from third_party/rapidyaml/rapidyaml/src/c4/yml/std/string.hpp:7,
                   from third_party/rapidyaml/rapidyaml/src/./c4/yml/std/std.hpp:4,
                   from third_party/rapidyaml/rapidyaml/src/ryml_std.hpp:4,
                   from core/vm.cpp:29:
  third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/compiler.hpp:90:13: error: #error "GCC < 5 is not supported"
   #           error "GCC < 5 is not supported"
               ^
  In file included from third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/config.hpp:37:0,
                   from third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/substr.hpp:10,
                   from third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/std/string.hpp:6,
                   from third_party/rapidyaml/rapidyaml/src/c4/yml/std/string.hpp:7,
                   from third_party/rapidyaml/rapidyaml/src/./c4/yml/std/std.hpp:4,
                   from third_party/rapidyaml/rapidyaml/src/ryml_std.hpp:4,
                   from core/vm.cpp:29:
  third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/types.hpp:221:19: error: ‘is_trivially_copyable’ is not a member of ‘std’
       static_assert(std::is_trivially_copyable<ty>::value, #ty " must be trivially copyable")
                     ^
  third_party/rapidyaml/rapidyaml/src/c4/yml/tree.hpp:269:1: note: in expansion of macro ‘C4_MUST_BE_TRIVIAL_COPY’
   C4_MUST_BE_TRIVIAL_COPY(NodeScalar);
   ^
  third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/types.hpp:221:48: error: expected primary-expression before ‘>’ token
       static_assert(std::is_trivially_copyable<ty>::value, #ty " must be trivially copyable")
                                                  ^
  third_party/rapidyaml/rapidyaml/src/c4/yml/tree.hpp:269:1: note: in expansion of macro ‘C4_MUST_BE_TRIVIAL_COPY’
   C4_MUST_BE_TRIVIAL_COPY(NodeScalar);
   ^
  third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/types.hpp:221:49: error: ‘::value’ has not been declared
       static_assert(std::is_trivially_copyable<ty>::value, #ty " must be trivially copyable")
                                                   ^
  third_party/rapidyaml/rapidyaml/src/c4/yml/tree.hpp:269:1: note: in expansion of macro ‘C4_MUST_BE_TRIVIAL_COPY’
   C4_MUST_BE_TRIVIAL_COPY(NodeScalar);
   ^
  third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/types.hpp:221:19: error: ‘is_trivially_copyable’ is not a member of ‘std’
       static_assert(std::is_trivially_copyable<ty>::value, #ty " must be trivially copyable")
                     ^
  third_party/rapidyaml/rapidyaml/src/c4/yml/tree.hpp:404:1: note: in expansion of macro ‘C4_MUST_BE_TRIVIAL_COPY’
   C4_MUST_BE_TRIVIAL_COPY(NodeData);
   ^
  third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/types.hpp:221:48: error: expected primary-expression before ‘>’ token
       static_assert(std::is_trivially_copyable<ty>::value, #ty " must be trivially copyable")
                                                  ^
  third_party/rapidyaml/rapidyaml/src/c4/yml/tree.hpp:404:1: note: in expansion of macro ‘C4_MUST_BE_TRIVIAL_COPY’
   C4_MUST_BE_TRIVIAL_COPY(NodeData);
   ^
  third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/types.hpp:221:49: error: ‘::value’ has not been declared
       static_assert(std::is_trivially_copyable<ty>::value, #ty " must be trivially copyable")
                                                   ^
  third_party/rapidyaml/rapidyaml/src/c4/yml/tree.hpp:404:1: note: in expansion of macro ‘C4_MUST_BE_TRIVIAL_COPY’
   C4_MUST_BE_TRIVIAL_COPY(NodeData);
   ^
  In file included from third_party/rapidyaml/rapidyaml/src/./c4/yml/./parse.hpp:13:0,
                   from third_party/rapidyaml/rapidyaml/src/./c4/yml/yml.hpp:7,
                   from third_party/rapidyaml/rapidyaml/src/ryml.hpp:4,
                   from core/vm.cpp:30:
  third_party/rapidyaml/rapidyaml/src/c4/yml/detail/stack.hpp:22:19: error: ‘is_trivially_copyable’ is not a member of ‘std’
       static_assert(std::is_trivially_copyable<T>::value, "T must be trivially copyable");
                     ^
  third_party/rapidyaml/rapidyaml/src/c4/yml/detail/stack.hpp:22:47: error: expected primary-expression before ‘>’ token
       static_assert(std::is_trivially_copyable<T>::value, "T must be trivially copyable");
                                                 ^
  third_party/rapidyaml/rapidyaml/src/c4/yml/detail/stack.hpp:22:48: error: ‘::value’ has not been declared
       static_assert(std::is_trivially_copyable<T>::value, "T must be trivially copyable");
                                                  ^
  make: *** [core/vm.o] Error 1
  Traceback (most recent call last):
    File "/anaconda3/envs/test/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "//anaconda3/envs/test/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/anaconda3/envs/test/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 416, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 79, in <module>
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
      self.run_command(cmd_name)
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/tmp/tmpj_azmex5/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "<string>", line 68, in run
  Exception: Could not build core/desugarer.o, core/formatter.o, core/libjsonnet.o, core/lexer.o, core/parser.o, core/pass.o, core/static_analysis.o, core/string_utils.o, core/vm.o, third_party/md5/md5.o, third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/char_traits.o, third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/base64.o, third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/language.o, third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/memory_util.o, third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/format.o, third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/time.o, third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/memory_resource.o, third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/error.o, third_party/rapidyaml/rapidyaml/src/c4/yml/parse.o, third_party/rapidyaml/rapidyaml/src/c4/yml/preprocess.o, third_party/rapidyaml/rapidyaml/src/c4/yml/common.o, third_party/rapidyaml/rapidyaml/src/c4/yml/tree.o
  

  at ~/anaconda3/envs/test/lib/python3.8/site-packages/poetry/installation/chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with jsonnet (0.18.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "jsonnet (==0.18.0)"'.
```

**Comment by RickRen-rpr** [comment]
I don't have problems with the notebook either, but when I install the environment in the server I encounter these problems, I'm not sure if it's related to my network

**Comment by RickRen-rpr** [comment]
## my Poetry version == 1.4.0
## my python version == 3.8.15

**Comment by JohnGiorgi** [comment]
Error says that `GCC < 5 is not supported`, so it looks like you will have to update it. You can check the current version with `gcc -v`. For example

My local env:

```
gcc -v
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Colab

```
!gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
```

In both cases, the version is >4

**Comment by RickRen-rpr** [comment]
Thank you very much for your reply, your reply is very helpful, but I now have a new problem, when I use poetry and download codecov==2.1.12, I encounter the following problem. I can't find that version of the package on my browser either, what changes do I need to make?
![image](https://github.com/JohnGiorgi/seq2rel/assets/58381711/5ad83929-2a1f-42b5-9cfc-0d418ac1bd5d)

**Comment by JohnGiorgi** [comment]
`codecov=2.1.12` is broken on my end too. Hmm, you don't actually need this to run seq2rel, so try installing with:

```
poetry install --without dev
```

**Comment by RickRen-rpr** [comment]
Thank you very much for your reply, it helped me a lot! Have a great life!

**Comment by wucui5** [comment]
Hello, I encountered the following problems while reproducing your model. The code for seq2rel and seq2rel-ds has been cloned, and poetry as well as allennlp have been downloaded. However, when I try to use the seq2rel-ds command, it can't be found. I'm not sure how to install the seq2rel-ds package. Looking forward to your reply!
<img width="671" alt="image" src="https://github.com/JohnGiorgi/seq2rel/assets/131764970/7973c3cc-e0a2-4bb6-92ea-8165bb8afe73">
